### ISSUE TITLE
Can't recreate environment with conda

### ISSUE THREAD

**Issue by jetsnguns** [izmailovpavel/bnn_covariate_shift#2]
Hello! I was trying to recreate the environment using `conda` and the file provided. Unfortunately, it didn't work. Maybe there are specific channels for the packages that are missing from the documentation?
Output is here:
<details>
  <summary>Log</summary>
    
    (base)  alex@xxx ~/bnn_covariate_shift> conda create -n izmailov --file requirements.txt 
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed
    
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - pyasn1==0.4.8=pypi_0
      - markdown==3.3.4=pypi_0
      - dm-tree==0.1.6=pypi_0
      - tensorboard-data-server==0.6.0=pypi_0
      - requests==2.25.1=pypi_0
      - opt-einsum==3.3.0=pypi_0
      - importlib-resources==5.1.2=pypi_0
      - keras-preprocessing==1.1.2=pypi_0
      - chardet==4.0.0=pypi_0
      - cachetools==4.2.2=pypi_0
      - chex==0.0.6=pypi_0
      - toolz==0.11.1=pypi_0
      - pyasn1-modules==0.2.8=pypi_0
      - jaxlib==0.1.65+cuda112=pypi_0
      - wrapt==1.12.1=pypi_0
      - requests-oauthlib==1.3.0=pypi_0
      - tabulate==0.8.9=pypi_0
      - protobuf==3.15.8=pypi_0
      - tensorflow-estimator==2.4.0=pypi_0
      - tqdm==4.60.0=pypi_0
      - absl-py==0.12.0=pypi_0
      - grpcio==1.32.0=pypi_0
      - jmp==0.0.2=pypi_0
      - six==1.15.0=pypi_0
      - promise==2.3=pypi_0
      - dm-haiku==0.0.5.dev0=pypi_0
      - tensorboard==2.5.0=pypi_0
      - flatbuffers==1.12=pypi_0
      - oauthlib==3.1.0=pypi_0
      - dill==0.3.3=pypi_0
      - tensorflow-datasets==4.2.0=pypi_0
      - google-pasta==0.2.0=pypi_0
      - gast==0.3.3=pypi_0
      - jax==0.2.12=pypi_0
      - astunparse==1.6.3=pypi_0
      - google-auth-oauthlib==0.4.4=pypi_0
      - h5py==2.10.0=pypi_0
      - scipy==1.6.3=pypi_0
      - urllib3==1.26.4=pypi_0
      - future==0.18.2=pypi_0
      - tensorflow-metadata==0.30.0=pypi_0
      - idna==2.10=pypi_0
      - termcolor==1.1.0=pypi_0
      - typing-extensions==3.7.4.3=pypi_0
      - rsa==4.7.2=pypi_0
      - numpy==1.19.5=pypi_0
      - tensorboard-plugin-wit==1.8.0=pypi_0
      - optax==0.0.6=pypi_0
      - attrs==20.3.0=pypi_0
      - googleapis-common-protos==1.53.0=pypi_0
      - pip==21.1=pypi_0
      - google-auth==1.30.0=pypi_0
      - werkzeug==1.0.1=pypi_0
      - tensorflow==2.4.1=pypi_0
    
    Current channels:
    
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.

 
</details>

**Comment by izmailovpavel** [comment]
Hi @jetsnguns sorry about that! I exported this file on google cloud machine, so I guess some of these packages might be specific to google cloud. Could you try to set up the environment using the `pip install` instructions?

**Comment by jetsnguns** [comment]
Thanks for the reply, @izmailovpavel ! Yes, `pip` installation works; I'll stick with it then.
