### ISSUE TITLE
Access to model checkpoint

### ISSUE THREAD

**Issue by xidulu** [izmailovpavel/bnn_covariate_shift#3]
Hi Pavel

This is very cool work! Unfortunately, I don't have access to TPUs or 8 V100s so I cannot reproduce your HMC inference.
It would be great if you can upload the HMC samples used in the MLP and CIFAR10 experiments in your paper.

Thanks!

**Comment by izmailovpavel** [comment]
Hi @xidulu! Actually, for all the MNIST experiments we used just a single GPU, so you might be able to run those!

For CIFAR, you can get access to the HMC samples for ResNet models here: https://colab.research.google.com/drive/1EAWv7KwVPh_bw3hvJOfCNappQTQgGsh7?usp=sharing.

If you need to access the MNIST checkpoints, I uploaded some of our MLP runs here: https://storage.cloud.google.com/neurips2021_bdl_competition/bnn_covshift_mnist_mlp_runs.tar.gz. Please let me know if you have any issues accessing these.

We plan to open-source more HMC checkpoints in the future.

**Comment by xidulu** [comment]
@izmailovpavel
Thanks! Are you also planning to open-source the LeNet checkpoint (with or without EmpCov Prior)?
If so, that would be very helpful!

**Comment by izmailovpavel** [comment]
Hi @xidulu, I re-ran HMC on MNIST CNN as you requested with these comands:

```bash
# Gaussian prior
python3 run_hmc.py --seed=2 --weight_decay=100  --dir=new_runs/hmc/mnist/gaussian \
--dataset_name=mnist --model_name=lenet --step_size=3.e-05 --trajectory_len=0.15 \
--num_iterations=100 --max_num_leapfrog_steps=5500 --num_burn_in_iterations=1

# EmpCov prior:
python3 run_hmc.py --seed=3 --weight_decay=100. --temperature=1. --dir=new_runs/hmc/mnist/EmpCov \
--dataset_name=mnist --model_name=lenet --step_size=1.e-4 --trajectory_len=0.157 \
--num_iterations=100 --max_num_leapfrog_steps=2000 --num_burn_in_iterations=10 \
--prior_family=EmpCovLeNet --empcov_invcov_ckpt=empcov_covs/mnist_cnn_pca_inv_cov.npy \
--empcov_wd=100.
```

I ran three chains of each. I uploaded the checkpoints here:
- MNIST CNN: https://storage.googleapis.com/bnn_covariate_shift/mnist_cnn_runs.tar.gz
- MNIST MLP: https://storage.googleapis.com/bnn_covariate_shift/mnist_mlp_runs.tar.gz

Alternative (google drive):
- MLP checkpoints: https://drive.google.com/file/d/1vztHk9eA2AcJ9ZcPmWIJq9e1x6K_yAda/view?usp=sharing
- CNN checkpoints: https://drive.google.com/file/d/15FTYKdyjSPx95BLai5shs6SB_Fu9TM6u/view?usp=sharing

On a single Titan RTX GPU, the Gaussian prior runs take 6 minutes / sample, and the EmpCov runs take 2 minutes / sample for the CNN.

Let me know if there are any issues with these checkpoints!

**Comment by xidulu** [comment]
@izmailovpavel 
Thanks! Really appreciate it!

**Comment by xidulu** [comment]
@izmailovpavel 
Hi 
Thanks for uploading the checkpoints! But I recently found out that I have difficulty downloading the checkpoints, when I opened the link, it says:
<img width="918" alt="Screen Shot 2022-03-26 at 12 59 46 PM" src="https://user-images.githubusercontent.com/26022201/160249735-3a63949b-84ed-43c2-a6de-041ab4f1f131.png">

Do you have any clue on why this would happen?

Thanks,
Xi
