### ISSUE TITLE
Checkpoint link invalid

### ISSUE THREAD

**Issue by xidulu** [izmailovpavel/bnn_covariate_shift#4]
Hi Pavel @izmailovpavel 

Thanks for uploading the checkpoints, but I recently found that the checkpoint link (https://storage.googleapis.com/bnn_covariate_shift/mnist_cnn_runs.tar.gz) is no longer valid, when I clicked the link, it said:
![Screen Shot 2022-03-26 at 1 03 12 PM](https://user-images.githubusercontent.com/26022201/160249864-68dbf171-028a-451a-8369-5d26927b3e70.png)

Is it possible to let me have access to the checkpoints?

Thanks,
Xi

**Comment by izmailovpavel** [comment]
Hi @xidulu!

Indeed, it seems like the google storage links stopped working for some reason. I am not sure why it happened, so I re-uploaded checkpoints to google drive:
- [MLP checkpoints](https://drive.google.com/file/d/1vztHk9eA2AcJ9ZcPmWIJq9e1x6K_yAda/view?usp=sharing)
- [CNN checkpoints](https://drive.google.com/file/d/15FTYKdyjSPx95BLai5shs6SB_Fu9TM6u/view?usp=sharing)

Please let me know if you have any issues.
